# Generated by Django 3.2.7 on 2023-01-19 20:57

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('motDePasse', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('membre', models.ForeignKey(on_delete=builtins.any, to='compteorgane.membre')),
                ('organe', models.ForeignKey(on_delete=builtins.any, to='compteorgane.organe')),
            ],
        ),
    ]
